// SPDX-FileCopyrightText: 2025 corresp0nd <46357632+corresp0nd@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Records.GenericRecordsConsole;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Records.GenericRecordsConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class GenericRecordsMenu : FancyWindow
{
    #region deps/events/etc
    public struct CharacterListMetadata
    {
        public uint CharacterRecordKey;
        public uint? StationRecordKey;
    }

    public event Action<CharacterListMetadata?>? OnListingItemSelected;
    public event Action<StationRecordFilterType, string?>? OnFiltersChanged;

    private RecordConsoleType? _type;
    private StationRecordFilterType _currentFilterType;
    private bool _isPopulating;

    /// <summary>
    /// The key to the record of the currently selected item in the listing.
    /// </summary>
    private uint? _selectedListingKey;

    // ui fragments
    private RecordsGeneralFragment _generalFragment = new();
    private RecordsEmploymentFragment _employmentFragment = new();
    private RecordsMedicalFragment _medicalFragment = new();
    private RecordsSecurityFragment _securityFragment = new();

    #endregion
    public GenericRecordsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // There is no reason why we can't just steal the StationRecordFilter class.
        // If wizden adds a new kind of filtering we want to replicate it here.
        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            RecordFilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        #region buttons

        CharacterListing.OnItemSelected += _ =>
        {
            if (!CharacterListing.GetSelected().Any())
                return;
            var selected = CharacterListing.GetSelected().First();
            var meta = (CharacterListMetadata)selected.Metadata!;
            _selectedListingKey = meta.CharacterRecordKey;
            if (!_isPopulating)
                OnListingItemSelected?.Invoke(meta);
        };

        CharacterListing.OnItemDeselected += _ =>
        {
            // When we populate the records, we clear the contents of the listing.
            // This could cause a deselection but we don't want to really deselect because it would
            // interrupt what the player is doing.

            if (!_isPopulating)
                OnListingItemSelected?.Invoke(null);

            _selectedListingKey = null;
        };

        // buttons to filter the crew list
        RecordFilters.OnPressed += _ =>
        {
            OnFiltersChanged?.Invoke(_currentFilterType, RecordFiltersValue.Text);
        };

        RecordFiltersReset.OnPressed += _ =>
        {
            OnFiltersChanged?.Invoke(StationRecordFilterType.Name, null);
            RecordFiltersValue.Clear();
        };

        RecordFiltersValue.OnTextEntered += text =>
        {
            OnFiltersChanged?.Invoke(_currentFilterType, text.Text);
        };

        RecordFilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;
            _currentFilterType = type;
            RecordFilterType.SelectId(eventArgs.Id);
        };

        #endregion

        CacheFragments();
    }

    public void UpdateState(GenericRecordsConsoleState state)
    {
        _type = state.ConsoleType;

        if (state.CharacterList == null)
        {
            CharacterListingStatus.Visible = true;
            CharacterListing.Visible = false;
            CharacterListingStatus.Text = "No data available";

            RecordContainer.Visible = false;
            RecordContainerStatus.Visible = true;
            return;
        }

        CharacterListingStatus.Visible = false;
        CharacterListing.Visible = true;

        if (state.Filter != null)
        {
            RecordFiltersValue.SetText(state.Filter.Value);
            RecordFilterType.SelectId((int)state.Filter.Type);
        }

        if (CharacterListNeedsRepopulating(state.CharacterList))
        {
            _isPopulating = true;

            CharacterListing.Clear();

            // Add the records to the listing in a sorted order. There is probably are faster way of doing this, but
            // this is not really a hot code path.
            state.CharacterList
                // The items in this tuple are as follows: (name of character, CharacterListMetadata)
                .Select(r
                    => (CharacterName: r.Value.CharacterDisplayName, new CharacterListMetadata() { CharacterRecordKey = r.Key, StationRecordKey = r.Value.StationRecordKey}))
                .OrderBy(r => r.Item1)
                .ToList()
                .ForEach(r => CharacterListing.AddItem(r.Item1, metadata: r.Item2));

            _isPopulating = false;
        }

        SelectRecordKey(state.SelectedIndex);

        // Enable container if we have a record selected
        if (state.SelectedRecord == null)
        {
            RecordContainerStatus.Visible = true;
            RecordContainer.Visible = false;
            return;
        }

        var record = state.SelectedRecord!;
        RecordContainerStatus.Visible = false;
        RecordContainer.Visible = true;

        RecordContainerName.Text = record.Name;
        _generalFragment.Visible = true;
        _generalFragment.Refresh(record);

        switch (_type)
        {
            case RecordConsoleType.Employment:
            {
                _employmentFragment.Visible = true;
                _employmentFragment.Refresh(record);
                break;
            }
            case RecordConsoleType.Medical:
            {
                _medicalFragment.Visible = true;
                _medicalFragment.Refresh(record);
                break;
            }
            case RecordConsoleType.Security:
            {
                _securityFragment.Visible = true;
                _securityFragment.Refresh(record, state.SelectedCriminal);
                break;
            }
            case RecordConsoleType.Admin:
                _employmentFragment.Visible = true;
                _employmentFragment.Refresh(record);
                _medicalFragment.Visible = true;
                _medicalFragment.Refresh(record);
                _securityFragment.Visible = true;
                _securityFragment.Refresh(record, state.SelectedCriminal);
                break;
        }
    }

    /// <summary>
    /// we don't know what kind of console this is yet, but we don't want to generate new fragments every time
    /// the character selected or state changes. so we cache the fragments first, then hide them
    /// </summary>
    private void CacheFragments()
    {
        RecordContainerFill.AddChild(_generalFragment);
        _generalFragment.Visible = false;

        RecordContainerFill.AddChild(_employmentFragment);
        _employmentFragment.Visible = false;

        RecordContainerFill.AddChild(_medicalFragment);
        _medicalFragment.Visible = false;

        RecordContainerFill.AddChild(_securityFragment);
        _securityFragment.Visible = false;
    }

    private bool CharacterListNeedsRepopulating(IReadOnlyDictionary<uint, GenericRecordsConsoleState.CharacterInfo> newKeys)
    {
        var newCount = newKeys.Count;
        if (newCount != CharacterListing.Count)
            return true;

        // Given that there is the same number of keys in the dictionary as in items in the listing, they are not equal
        // if and only if there exists a key in the listing that is not in the dictionary
        return CharacterListing
            .Select(item => ((CharacterListMetadata) item.Metadata!).CharacterRecordKey)
            .Any(key => !newKeys.ContainsKey(key));
    }

    // If we are using wizden's class we might as well use their localization.
    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }

    /// <summary>
    /// Select the record in the listing for the given key.
    /// </summary>
    /// <param name="key">The index of the record in the dictionary</param>
    private void SelectRecordKey(uint? key)
    {
        if (_selectedListingKey == key)
            return;

        _selectedListingKey = key;
        _isPopulating = true;
        CharacterListing.ClearSelected();

        // I wish there was a better way of doing this
        if (key != null)
        {
            foreach (var item in CharacterListing)
            {
                if (((CharacterListMetadata) item.Metadata!).CharacterRecordKey == key)
                {
                    item.Selected = true;
                    break;
                }
            }
        }

        _isPopulating = false;
    }

    public bool IsSecurity()
    {
        return _type is RecordConsoleType.Security or RecordConsoleType.Admin;
    }
}
