using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Records;
using Content.Shared._Funkystation.Security;
using Content.Shared.Administration;
using Content.Shared.CriminalRecords;
using Content.Shared.Dataset;
using Content.Shared.Random.Helpers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client._Funkystation.Records.GenericRecordsConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordsSecurityFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IRobustRandom _random = default!;
    public event Action<ProtoId<SecurityStatusPrototype>, string?>? OnSetSecurityStatus;
    private DialogWindow? _dialog;

    private readonly Dictionary<SecurityStatusPrototype, int> _statusSelectorOptions = new();
    private readonly Dictionary<int, SecurityStatusPrototype> _statusSelectorOptionsReverse = new();
    private static readonly ProtoId<LocalizedDatasetPrototype> ReasonPlaceholders = "CriminalRecordsWantedReasonPlaceholders";

    public RecordsSecurityFragment(FullCharacterRecords record, CriminalRecord? criminal)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StatusOptionButton.OnItemSelected += args =>
        {
            SetStatus(_statusSelectorOptionsReverse[args.Id]);
        };

        foreach (var status in _proto.EnumeratePrototypes<SecurityStatusPrototype>().ToList().OrderByDescending(o => o.Priority).ToList())
        {
            AddStatusSelect(status);
        }

        UpdateState(record, criminal);
    }

    public void UpdateState(FullCharacterRecords record, CriminalRecord? criminal)
    {
        SetValue(record, criminal);
    }

    private void AddStatusSelect(SecurityStatusPrototype status)
    {
        var name = status.LocalizedName;
        var id = _statusSelectorOptions.Count;
        _statusSelectorOptions.Add(status, id);
        _statusSelectorOptionsReverse.Add(id, status);
        StatusOptionButton.AddItem(name, id);
    }

    private void SetValue(FullCharacterRecords record, CriminalRecord? criminal)
    {
        RecordContainerFingerprints.Text = record.Fingerprint ?? Loc.GetString("funky-records-viewer-unknown");
        RecordContainerDNA.Text = record.DNA ?? Loc.GetString("funky-records-viewer-unknown");

        WantedReason.Title = Loc.GetString("funky-records-wanted-title");
        WantedReason.Visible = false;

        if (criminal == null)
            return;

        var criminalStatus = _proto.Index(criminal.Status);
        StatusOptionButton.SelectId(_statusSelectorOptions[criminalStatus]);
        WantedReason.Visible = criminal.Reason != null;

        if (criminal.Reason != null)
            WantedReason.SetValue("[color=white]" + criminal.Reason + "[/color]");
    }

    public void SetSecurityStatusEnabled(bool setting)
    {
        for (var i = 0; i < StatusOptionButton.ItemCount; ++i)
        {
            StatusOptionButton.SetItemDisabled(i, !setting);
        }
    }

    private void SetStatus(SecurityStatusPrototype status)
    {
        if (status.RequiresReason)
        {
            GetReason(status);
            return;
        }

        OnSetSecurityStatus?.Invoke(status, null);
    }

    private void GetReason(SecurityStatusPrototype status)
    {
        if (_dialog != null)
        {
            _dialog.MoveToFront();
            return;
        }

        var field = "reason";
        var title = status.LocalizedName;
        var placeholders = _proto.Index(ReasonPlaceholders);
        var placeholder = Loc.GetString("criminal-records-console-reason-placeholder", ("placeholder", _random.Pick(placeholders))); // just funny it doesn't actually get used
        var prompt = Loc.GetString("criminal-records-console-reason");
        var entry = new QuickDialogEntry(field, QuickDialogEntryType.LongText, prompt, placeholder);
        var entries = new List<QuickDialogEntry>() { entry };
        _dialog = new DialogWindow(title, entries);

        _dialog.OnConfirmed += responses =>
        {
            var reason = responses[field];
            if (reason.Length is < 1 or > 248)
                return;

            OnSetSecurityStatus?.Invoke(status, reason);
        };

        _dialog.OnClose += () => { _dialog = null; };
    }

    public void UpdateHistory(CriminalRecord record, bool access)
    {
        History.Clear();
        // todo finish this
    }
}
