using System.Linq;
using Content.Client._CD.Records.UI;
using Content.Shared._Funkystation.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.Records.GenericRecordsConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordsEmploymentFragment : BoxContainer
{
    public RecordsEmploymentFragment(FullCharacterRecords record)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Refresh(record);
    }

    public void Refresh(FullCharacterRecords record)
    {
        var cr = record.PRecords;

        RecordContainerWorkAuth.Text = cr.HasWorkAuthorization ? Loc.GetString("funky-records-yes") : Loc.GetString("funky-records-no");
        RecordContainerInsurance.Text = cr.HasInsurance ? Loc.GetString("funky-records-yes") : Loc.GetString("funky-records-no");
        RecordContainerInsuranceProvider.Text = GetInsuranceProviderLocals(cr.InsuranceProvider);
        RecordContainerInsurancePlan.Text = GetInsuranceTypeLocals(cr.InsuranceType);
        InsuranceContainer.Visible = RecordContainerInsurance.Text.Equals(Loc.GetString("funky-records-yes"));
    }

    private string GetInsuranceProviderLocals(int id)
    {
        var type = (InsuranceProviders)id;
        return Loc.GetString($"character-records-insurance-provider-{type.ToString().ToLower()}");
    }

    private string GetInsuranceTypeLocals(int id)
    {
        var type = (InsuranceTypes)id;
        return Loc.GetString($"character-records-insurance-type-{type.ToString().ToLower()}");
    }
}
