using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Records;
using Content.Shared.Administration;
using Content.Shared.CriminalRecords;
using Content.Shared.Security;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Records.GenericRecordsConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordsSecurityFragment : BoxContainer
{
    public event Action<SecurityStatus, string?>? OnSetSecurityStatus;

    private DialogWindow? _dialog;

    public RecordsSecurityFragment(FullCharacterRecords? record, (SecurityStatus, string?)? criminal)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StatusOptionButton.OnItemSelected += args =>
        {
            var status = (SecurityStatus)args.Id;
            // This should reflect SetStatus in CriminalRecordsConsoleWindow.xaml.cs
            if (status is SecurityStatus.Wanted or SecurityStatus.Suspected)
                SetStatusWithReason(status);
            else
                OnSetSecurityStatus?.Invoke(status, null);
        };

        foreach (var status in Enum.GetValues<SecurityStatus>())
        {
            var name = Loc.GetString($"criminal-records-status-{status.ToString().ToLower()}");
            StatusOptionButton.AddItem(name, (int)status);
        }

        if (record != null)
            SetValue(record, criminal);
    }

    public void Refresh(FullCharacterRecords record, (SecurityStatus, string?)? criminal)
    {
        SetValue(record, criminal);
    }

    private void SetValue(FullCharacterRecords record, (SecurityStatus, string?)? criminal)
    {
        RecordContainerFingerprints.Text = record.Fingerprint ?? Loc.GetString("funky-records-viewer-unknown");
        RecordContainerDNA.Text = record.DNA ?? Loc.GetString("funky-records-viewer-unknown");

        WantedReason.Title = Loc.GetString("funky-records-wanted-title");
        WantedReason.Visible = false;

        if (criminal == null)
            return;

        var (stat, reason) = criminal.Value;
        StatusOptionButton.Select((int)stat);
        WantedReason.Visible = reason != null;

        if (reason != null)
            WantedReason.SetValue("[color=white]" + reason + "[/color]");
    }

    public void SetSecurityStatusEnabled(bool setting)
    {
        for (var i = 0; i < StatusOptionButton.ItemCount; ++i)
        {
            StatusOptionButton.SetItemDisabled(i, !setting);
        }
    }


    // This is copied almost verbatim from CriminalRecordsConsoleWindow.xaml.cs
    private void SetStatusWithReason(SecurityStatus status)
    {
        if (_dialog != null)
        {
            _dialog.MoveToFront();
            return;
        }

        const string field = "reason";
        var title = Loc.GetString("criminal-records-status-" + status.ToString().ToLower());
        var placeholder = Loc.GetString("funky-records-viewer-setwanted-placeholder");
        var prompt = Loc.GetString("criminal-records-console-reason");
        var entry = new QuickDialogEntry(field, QuickDialogEntryType.LongText, prompt, placeholder);
        var entries = new List<QuickDialogEntry>() { entry };
        _dialog = new DialogWindow(title, entries);

        _dialog.OnConfirmed += responses =>
        {
            var reason = responses[field];
            if (reason.Length < 1)
                return;

            OnSetSecurityStatus?.Invoke(status, reason);
        };

        _dialog.OnClose += () => { _dialog = null; };
    }

    public void UpdateHistory(CriminalRecord record, bool access)
    {
        History.Clear();
        // todo finish this
    }
}
