using System.Linq;
using Content.Client._CD.Records.UI;
using Content.Shared._Funkystation.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.Records.GenericRecordsConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordsMedicalFragment : BoxContainer
{
    // i am NOT making a whole style sheet for these icons right now. sorry.
    // maybe next week style funky will be real
    private const string ArrowUp = "/Textures/_Funkystation/Interface/StyleFunky/arrow_up.png";
    private const string ArrowDown = "/Textures/_Funkystation/Interface/StyleFunky/arrow_down.png";

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public RecordsMedicalFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HeaderButton.OnButtonUp += _ =>
        {
            RecordsContent.Visible = !RecordsContent.Visible;
            HeaderButtonArrow.TexturePath = RecordsContent.Visible ? ArrowUp : ArrowDown;
        };
    }

    public void Refresh(FullCharacterRecords record)
    {
        // record = base wizden information
        // cr = extra flavor info added from cosmatic drift
        var cr = record.PRecords;

        RecordContainerBloodType.Text = GetBloodTypeLocals(cr.BloodType);
        RecordContainerIdentFeatures.Title = Loc.GetString("funky-records-identifying-features-title");
        RecordContainerIdentFeatures.SetValue(cr.IdentifyingFeatures == "" ? Loc.GetString("funky-records-viewer-unknown") : cr.IdentifyingFeatures);
        RecordContainerPostMortem.Title = Loc.GetString("funky-records-post-mortem-title");
        RecordContainerPostMortem.SetValue(cr.PostmortemInstructions);
        RefreshMedicalInformation(cr.MedicalInfo);

        RecordContainerInsurance.Text = cr.HasInsurance ? Loc.GetString("funky-records-yes") : Loc.GetString("funky-records-no");
        RecordContainerInsuranceProvider.Text = GetInsuranceProviderLocals(cr.InsuranceProvider);
        RecordContainerInsurancePlan.Text = GetInsuranceTypeLocals(cr.InsuranceType);
        InsuranceContainer.Visible = RecordContainerInsurance.Text.Equals(Loc.GetString("funky-records-yes"));
    }

    /// <summary>
    /// organizes the given medical info into a hashmap, then assigns each category to
    /// its corresponding ui element
    /// </summary>
    private void RefreshMedicalInformation(HashSet<ProtoId<MedicalInfoPrototype>> medicalInfo)
    {
        MedicalInfoContainer.DisposeAllChildren();

        var information = _prototypeManager.EnumeratePrototypes<MedicalInfoPrototype>()
            .OrderBy(t => Loc.GetString(t.Name))
            .ToList();

        Dictionary<string, List<string>> infoGroups = new();

        // this is just so it generates empty groups, rather than none at all, if a character does not have entries in that category.
        var allGroups = _prototypeManager.EnumeratePrototypes<MedicalInfoCategoryPrototype>()
            .OrderBy(t => Loc.GetString(t.Name))
            .ToList();

        foreach (var kind in allGroups)
            infoGroups.GetOrNew(kind.ID);

        foreach (var item in information)
        {
            // we don't need prototypes without an assigned category,
            // so just dump them instead of adding a default group
            if (item.Category == null)
                continue;

            if (!_prototypeManager.HasIndex(item.Category))
                continue;

            // if the given record doesn't have this prototype, skip it
            if (!medicalInfo.Contains(item.ID))
                continue;

            var group = infoGroups.GetOrNew(item.Category);
            group.Add(Loc.GetString(item.Name));
        }

        // build the ui
        // ill be so fr all of the stuff with setting the font colors is kinda shitcode
        // not like richtextlabels are particularly fun to use
        foreach (var (categoryId, categoryItems) in infoGroups)
        {
            if (!_prototypeManager.TryIndex<MedicalInfoCategoryPrototype>(categoryId, out var category))
                continue;

            if (category.ID == MedicalInfoCategoryPrototype.Default)
                continue;

            var item = new RecordLongItemDisplay()
            {
                Title = Loc.GetString(category.Name) + ": ",
                Margin = new Thickness(5),
            };

            var text = string.Join(", ", categoryItems);
            item.SetValue(text == ""
                ? Loc.GetString("funky-records-viewer-none-provided")
                : text);

            MedicalInfoContainer.AddChild(item);
        }
    }

    private static string GetBloodTypeLocals(int id)
    {
        var type = (BloodTypes)id;
        return Loc.GetString($"character-records-blood-{type.ToString().ToLower()}");
    }

    private string GetInsuranceProviderLocals(int id)
    {
        var type = (InsuranceProviders)id;
        return Loc.GetString($"character-records-insurance-provider-{type.ToString().ToLower()}");
    }

    private string GetInsuranceTypeLocals(int id)
    {
        var type = (InsuranceTypes)id;
        return Loc.GetString($"character-records-insurance-type-{type.ToString().ToLower()}");
    }
}
