using System.Linq;
using Content.Client._CD.Records.UI;
using Content.Shared._Funkystation.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.Records.GenericRecordsConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordsGeneralFragment : BoxContainer
{
    public RecordsGeneralFragment(FullCharacterRecords record)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Refresh(record);
    }

    public void Refresh(FullCharacterRecords record)
    {
        var cr = record.PRecords;

        RecordContainerJob.Text = record.JobTitle; /* At some point in the future we might want to display the icon */
        RecordContainerGender.Text = record.Gender.ToString();
        RecordContainerSpecies.Text = record.Species;
        RecordContainerAge.Text = record.Age.ToString();
        RecordContainerHeight.Text = cr.Height + " " + Loc.GetString("funky-records-unit-cm") + " " + UnitConversion.GetImperialDisplayLength(cr.Height);
        RecordContainerWeight.Text = cr.Weight + " " + Loc.GetString("funky-records-unit-kg") + " " + UnitConversion.GetImperialDisplayMass(cr.Weight);
    }
}
